export default [
  {
    _id: "uhqgy8gqywgy",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Impedit hic modi quia perspiciatis in sunt voluptate architecto, quas quae reprehenderit repellat voluptatum reiciendis quo repellendus laborum magni provident odio unde?",
    medias: [
      "https://picsum.photos/200/300",
      "https://picsum.photos/200/300",
      "https://picsum.photos/200/300",
    ],
    owner: {},
    likes: 0,
    comments: 0,
    saves: 0,
    title: "Product I - This is product one",
    website: "https://google.com",
    price: 22000,
    type: "product",
    category: "books_and_media",
    sub_category: "",
    created_at: new Date().toISOString(),
    is_liked_by_user: false,
    is_saved_by_user: false,
  },
  {
    _id: "uhgy8gqywgy",
    description:
      "  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Impedit hic modi quia perspiciatis in sunt voluptate architecto, quas quae reprehenderit repellat voluptatum reiciendis quo repellendus laborum magni provident odio unde?",
    medias: [
      "https://picsum.photos/200/300",
      "https://picsum.photos/200/300",
      "https://picsum.photos/200/300",
    ],
    owner: {},
    likes: 0,
    comments: 0,
    saves: 0,
    title: "Product II - This is product one",
    website: "https://google.com",
    price: 2000,
    type: "product",
    category: "books_and_media",
    sub_category: "",
    created_at: new Date().toISOString(),
    is_liked_by_user: false,
    is_saved_by_user: false,
  },
  {
    _id: "uhqgy8gqywg",
    description:
      "  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Impedit hic modi quia perspiciatis in sunt voluptate architecto, quas quae reprehenderit repellat voluptatum reiciendis quo repellendus laborum magni provident odio unde?",
    medias: [
      "https://picsum.photos/200/300",
      "https://picsum.photos/200/300",
      "https://picsum.photos/200/300",
    ],
    owner: {},
    likes: 0,
    comments: 0,
    saves: 0,
    title: "Nike shoes for dogs and cats",
    website: "https://google.com",
    price: 14000,
    type: "product",
    category: "books_and_media",
    sub_category: "",
    created_at: new Date().toISOString(),
    is_liked_by_user: false,
    is_saved_by_user: false,
  },
  {
    _id: "uhqgy8ggy",
    description:
      "  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Impedit hic modi quia perspiciatis in sunt voluptate architecto, quas quae reprehenderit repellat voluptatum reiciendis quo repellendus laborum magni provident odio unde?",
    medias: [
      "https://picsum.photos/200/300",
      "https://picsum.photos/200/300",
      "https://picsum.photos/200/300",
    ],
    owner: {},
    likes: 0,
    comments: 0,
    saves: 0,
    title: "Product unknown right now",
    website: "https://google.com",
    price: 12000,
    type: "product",
    category: "books_and_media",
    sub_category: "",
    created_at: new Date().toISOString(),
    is_liked_by_user: false,
    is_saved_by_user: false,
  },
  {
    _id: "uy8gqywgy",
    description:
      "  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Impedit hic modi quia perspiciatis in sunt voluptate architecto, quas quae reprehenderit repellat voluptatum reiciendis quo repellendus laborum magni provident odio unde?",
    medias: [
      "https://picsum.photos/200/300",
      "https://picsum.photos/200/300",
      "https://picsum.photos/200/300",
    ],
    owner: {},
    likes: 0,
    comments: 0,
    saves: 0,
    title: "Product III",
    website: "https://google.com",
    price: 12000,
    type: "product",
    category: "books_and_media",
    sub_category: "",
    created_at: new Date().toISOString(),
    is_liked_by_user: false,
    is_saved_by_user: false,
  },
];
