export default {
  website_icon: require("../../assets/images/website_icon.svg"),
  description_icon: require("../../assets/images/description_icon.svg"),
  clock_icon: require("../../assets/images/time_icon.svg"),
  male_placeholder: require("../../assets/images/male_placeholder.svg"),
  female_placeholder: require("../../assets/images/female_placeholder.svg"),
  unknown_placeholder: require("../../assets/images/unknown_placeholder.svg"),
  personal_details: require("../../assets/images/details_icon.svg"),
  save_icon: require("../../assets/images/save_icon.svg"),
  suggestions_icon: require("../../assets/images/suggestions_icon.svg"),
  privacy_icon: require("../../assets/images/privacy_icon.svg"),
  switch_icon: require("../../assets/images/switch_icon.svg"),
  logout_icon: require("../../assets/images/logout_icon.svg"),
  archive_icon: require("../../assets/images/archive_icon.svg"),
  preferences_icon: require("../../assets/images/preferences_icon.svg"),
  posts_icon: require("../../assets/images/posts_icon.svg"),
  repost_icon: require("../../assets/images/repost_icon.svg"),
  videos_icon: require("../../assets/images/videos_icon.svg"),
  shop_icon: require("../../assets/images/shop_icon.svg"),
  password_icon: require("../../assets/images/password_icon.svg"),
  premium_icon: require("../../assets/images/premium_icon.png"),
  contact_us_icon: require("../../assets/images/contact_us_icon.png"),
};
